//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StringResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is missing in token.
        /// </summary>
        internal static string BRAND_MISSING {
            get {
                return ResourceManager.GetString("BRAND_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call api cancelOrder to cancel an order..
        /// </summary>
        internal static string CALL_API_CANCEL {
            get {
                return ResourceManager.GetString("CALL_API_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li &amp; Fung Global Hotels.
        /// </summary>
        internal static string Globalhotel {
            get {
                return ResourceManager.GetString("Globalhotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请转到Web后台发货.
        /// </summary>
        internal static string GO_WEB_BACKEND_TO_SHIP {
            get {
                return ResourceManager.GetString("GO_WEB_BACKEND_TO_SHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面試評估表.
        /// </summary>
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的OrderId.
        /// </summary>
        internal static string INVALID_ORDER_ID {
            get {
                return ResourceManager.GetString("INVALID_ORDER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假期申請表.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to cancel this order.
        /// </summary>
        internal static string NOT_ALLOWED_CANCEL_ORDER {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_CANCEL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你不被允许抢这单.
        /// </summary>
        internal static string NOT_ALLOWED_GRAB_ORDER {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_GRAB_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change a cancelled order&apos;s status.
        /// </summary>
        internal static string NOT_CHANGE_CANCEL_ORDER_STATUS {
            get {
                return ResourceManager.GetString("NOT_CHANGE_CANCEL_ORDER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  订单已取消或者已经删除.
        /// </summary>
        internal static string ORDER_CANCELLED_DELETED {
            get {
                return ResourceManager.GetString("ORDER_CANCELLED_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单已经被抢.
        /// </summary>
        internal static string ORDER_EXPIRED {
            get {
                return ResourceManager.GetString("ORDER_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单已经被抢.
        /// </summary>
        internal static string ORDER_GRABBED {
            get {
                return ResourceManager.GetString("ORDER_GRABBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单已经取消，无法再次取消..
        /// </summary>
        internal static string ORDER_HAS_BEEN_CANCEL {
            get {
                return ResourceManager.GetString("ORDER_HAS_BEEN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单未找到或者数据不正确.
        /// </summary>
        internal static string ORDER_INVALID {
            get {
                return ResourceManager.GetString("ORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单未找到.
        /// </summary>
        internal static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter stockouts is missing.
        /// </summary>
        internal static string PARAMETER_STOCKOUTS_MISSING {
            get {
                return ResourceManager.GetString("PARAMETER_STOCKOUTS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同一店铺多只能抢一次.
        /// </summary>
        internal static string SHOP_GRAB_ONE_TIME {
            get {
                return ResourceManager.GetString("SHOP_GRAB_ONE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop is missing in token.
        /// </summary>
        internal static string SHOP_MISSING {
            get {
                return ResourceManager.GetString("SHOP_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店铺不存在.
        /// </summary>
        internal static string SHOP_NOT_FOUND {
            get {
                return ResourceManager.GetString("SHOP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利豐集團員購特約商店.
        /// </summary>
        internal static string SpecialStore {
            get {
                return ResourceManager.GetString("SpecialStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文具申请表.
        /// </summary>
        internal static string Stationery {
            get {
                return ResourceManager.GetString("Stationery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Design approval form.
        /// </summary>
        internal static string StoreDesign {
            get {
                return ResourceManager.GetString("StoreDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试-子步骤-全部通过.
        /// </summary>
        internal static string TestAll {
            get {
                return ResourceManager.GetString("TestAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试-子步骤-任意通过.
        /// </summary>
        internal static string TestAny {
            get {
                return ResourceManager.GetString("TestAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid token..
        /// </summary>
        internal static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token is missing..
        /// </summary>
        internal static string TOKEN_MISSING {
            get {
                return ResourceManager.GetString("TOKEN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 國外出差申請表.
        /// </summary>
        internal static string TravelAbroad {
            get {
                return ResourceManager.GetString("TravelAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法取消此订单.
        /// </summary>
        internal static string UNABLE_CANCEL_ORDER {
            get {
                return ResourceManager.GetString("UNABLE_CANCEL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法抢单，请重试.
        /// </summary>
        internal static string UNABLE_GRAB_ORDER {
            get {
                return ResourceManager.GetString("UNABLE_GRAB_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法更新订单状态..
        /// </summary>
        internal static string UNABLE_UPDATE_ORDER_STATUS {
            get {
                return ResourceManager.GetString("UNABLE_UPDATE_ORDER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法更新数据.
        /// </summary>
        internal static string UPDATE_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_FAILED", resourceCulture);
            }
        }
    }
}
