//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalUserView
    {
        public string Country { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNo { get; set; }
        public string EmpStatus { get; set; }
        public string EmpType { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Brand { get; set; }
        public string Dept { get; set; }
        public string DeptType { get; set; }
        public string ShopCode { get; set; }
    }
}
