//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInfo
    {
        public int StaffInfoId { get; set; }
        public string StaffId { get; set; }
        public string EnglishFirstName { get; set; }
        public string EnglishLastName { get; set; }
        public string LocalFirstName { get; set; }
        public string LocalLastName { get; set; }
        public string ResidentialAddress { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string HomeTelephone { get; set; }
        public string MobileTelephone { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string MaritalStatus { get; set; }
        public string FamilyMembers { get; set; }
        public string Qualification { get; set; }
        public string EmailAddress { get; set; }
        public string PreviousData { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
    }
}
