//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLogs
    {
        public int LogId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> LogTypeId { get; set; }
        public string LogTitle { get; set; }
        public string Parameter { get; set; }
    }
}
