//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_CountryArchivePaths
    {
        public int FlowGroupId { get; set; }
        public string CountryCode { get; set; }
        public string ApprovedArchivePath { get; set; }
    
        public virtual WF_FlowGroups WF_FlowGroups { get; set; }
    }
}
