//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_CaseNotifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_CaseNotifications()
        {
            this.WF_CaseNotificationReceivers = new HashSet<WF_CaseNotificationReceivers>();
        }
    
        public int CaseNotificationId { get; set; }
        public int NotificationType { get; set; }
        public int FlowCaseId { get; set; }
        public Nullable<int> FlowStepId { get; set; }
        public string Source { get; set; }
        public string Comments { get; set; }
        public string Sender { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseNotificationReceivers> WF_CaseNotificationReceivers { get; set; }
        public virtual WF_FlowSteps WF_FlowSteps { get; set; }
        public virtual WF_FlowCases WF_FlowCases { get; set; }
    }
}
