//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FlowTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_FlowTypes()
        {
            this.WF_FlowGroups = new HashSet<WF_FlowGroups>();
        }
    
        public int FlowTypeId { get; set; }
        public string Name { get; set; }
        public string Dep { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Creator { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public string Icon { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public string IconUrl { get; set; }
        public string Platform { get; set; }
        public string Tabs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowGroups> WF_FlowGroups { get; set; }
    }
}
