//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FlowSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_FlowSteps()
        {
            this.WF_CaseNotifications = new HashSet<WF_CaseNotifications>();
            this.WF_CaseUserActions = new HashSet<WF_CaseUserActions>();
            this.WF_NoApproverConditions = new HashSet<WF_NoApproverConditions>();
            this.WF_Secretary = new HashSet<WF_Secretary>();
        }
    
        public int FlowStepId { get; set; }
        public int StepGroupId { get; set; }
        public string Department { get; set; }
        public string UserNo { get; set; }
        public Nullable<int> ApproverType { get; set; }
        public int OrderId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<int> ManagerOption { get; set; }
        public Nullable<int> ManagerLevel { get; set; }
        public Nullable<int> ManagerMaxLevel { get; set; }
        public string ManagerLevelOperator { get; set; }
        public string CriteriaGradeOperator { get; set; }
        public Nullable<int> CriteriaGrade { get; set; }
        public Nullable<int> CountryType { get; set; }
        public Nullable<int> DeptType { get; set; }
        public Nullable<int> BrandType { get; set; }
        public Nullable<int> DeptTypeSource { get; set; }
        public string FixedCountry { get; set; }
        public string FixedDept { get; set; }
        public string FixedBrand { get; set; }
        public string FixedDeptType { get; set; }
        public Nullable<bool> NoApprover { get; set; }
        public Nullable<int> NoApproverDataKey { get; set; }
        public string NoApproverOperator { get; set; }
        public string NoApproverValue { get; set; }
        public string NoApproverMaxValue { get; set; }
        public string NotifyUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseNotifications> WF_CaseNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseUserActions> WF_CaseUserActions { get; set; }
        public virtual WF_StepGroups WF_StepGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_NoApproverConditions> WF_NoApproverConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_Secretary> WF_Secretary { get; set; }
    }
}
