//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FlowGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_FlowGroups()
        {
            this.WF_CountryArchivePaths = new HashSet<WF_CountryArchivePaths>();
            this.WF_FlowPropertys = new HashSet<WF_FlowPropertys>();
            this.WF_Flows = new HashSet<WF_Flows>();
        }
    
        public int FlowGroupId { get; set; }
        public int FlowTypeId { get; set; }
        public int Version { get; set; }
        public Nullable<bool> HasCoverUsers { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public string ApprovedArchivePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CountryArchivePaths> WF_CountryArchivePaths { get; set; }
        public virtual WF_FlowTypes WF_FlowTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowPropertys> WF_FlowPropertys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_Flows> WF_Flows { get; set; }
    }
}
