//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FlowCases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_FlowCases()
        {
            this.WF_CaseCoverUsers = new HashSet<WF_CaseCoverUsers>();
            this.WF_CaseLogs = new HashSet<WF_CaseLogs>();
            this.WF_CaseNotificateUsers = new HashSet<WF_CaseNotificateUsers>();
            this.WF_CaseNotifications = new HashSet<WF_CaseNotifications>();
            this.WF_CasePropertyValues = new HashSet<WF_CasePropertyValues>();
            this.WF_CaseSteps = new HashSet<WF_CaseSteps>();
            this.WF_CaseUserActions = new HashSet<WF_CaseUserActions>();
            this.WF_FlowCases_Attachments = new HashSet<WF_FlowCases_Attachments>();
        }
    
        public int FlowCaseId { get; set; }
        public int FlowId { get; set; }
        public string UserNo { get; set; }
        public string Subject { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public int IsRead { get; set; }
        public int IsFlagged { get; set; }
        public int IsDissmissed { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<System.DateTime> Rejected { get; set; }
        public Nullable<int> CurrentStepGroup { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> ReviseAbort { get; set; }
        public Nullable<int> Ver { get; set; }
        public Nullable<int> BaseFlowCaseId { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public Nullable<System.DateTime> LastApproverViewed { get; set; }
        public System.DateTime LastChecked { get; set; }
        public Nullable<int> RelatedFlowCaseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseCoverUsers> WF_CaseCoverUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseLogs> WF_CaseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseNotificateUsers> WF_CaseNotificateUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseNotifications> WF_CaseNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CasePropertyValues> WF_CasePropertyValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseSteps> WF_CaseSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CaseUserActions> WF_CaseUserActions { get; set; }
        public virtual WF_Flows WF_Flows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowCases_Attachments> WF_FlowCases_Attachments { get; set; }
        public virtual WF_StepGroups WF_StepGroups { get; set; }
    }
}
