//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FlowPropertys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_FlowPropertys()
        {
            this.WF_CasePropertyValues = new HashSet<WF_CasePropertyValues>();
            this.WF_FlowConditions = new HashSet<WF_FlowConditions>();
            this.WF_StepConditions = new HashSet<WF_StepConditions>();
        }
    
        public int FlowPropertyId { get; set; }
        public int PropertyType { get; set; }
        public string PropertyName { get; set; }
        public bool Compulsory { get; set; }
        public string DataSource { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> FlowGroupId { get; set; }
        public Nullable<int> Code { get; set; }
        public string ViewType { get; set; }
        public string Tab { get; set; }
        public Nullable<int> RowIndex { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public string Text { get; set; }
        public Nullable<bool> AllowMultiple { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string HAlign { get; set; }
        public string VAlign { get; set; }
        public string FontColor { get; set; }
        public string Validation { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string ValidationMsg { get; set; }
        public string BgColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_CasePropertyValues> WF_CasePropertyValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowConditions> WF_FlowConditions { get; set; }
        public virtual WF_FlowGroups WF_FlowGroups { get; set; }
        public virtual WF_TemplatePropCode WF_TemplatePropCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_StepConditions> WF_StepConditions { get; set; }
    }
}
