//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_StepGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_StepGroups()
        {
            this.WF_FlowSteps = new HashSet<WF_FlowSteps>();
            this.WF_StepGroupConditions = new HashSet<WF_StepGroupConditions>();
            this.WF_StepNotificateUsers = new HashSet<WF_StepNotificateUsers>();
            this.WF_FlowCases = new HashSet<WF_FlowCases>();
        }
    
        public int StepGroupId { get; set; }
        public int FlowId { get; set; }
        public int ConditionId { get; set; }
        public int OrderId { get; set; }
        public Nullable<bool> IsAllowModify { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public int StatusId { get; set; }
        public string ConditionRelation { get; set; }
    
        public virtual WF_Flows WF_Flows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowSteps> WF_FlowSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_StepGroupConditions> WF_StepGroupConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_StepNotificateUsers> WF_StepNotificateUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_FlowCases> WF_FlowCases { get; set; }
    }
}
