//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowLib.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkFlowEntities : DbContext
    {
        public WorkFlowEntities()
            : base("name=WorkFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StaffInfo> StaffInfo { get; set; }
        public virtual DbSet<SystemLogs> SystemLogs { get; set; }
        public virtual DbSet<UserDeviceTokens> UserDeviceTokens { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WF_ApplicantNotificationUsers> WF_ApplicantNotificationUsers { get; set; }
        public virtual DbSet<WF_CaseCoverUsers> WF_CaseCoverUsers { get; set; }
        public virtual DbSet<WF_CaseLogs> WF_CaseLogs { get; set; }
        public virtual DbSet<WF_CaseNotificateUsers> WF_CaseNotificateUsers { get; set; }
        public virtual DbSet<WF_CaseNotificationReceivers> WF_CaseNotificationReceivers { get; set; }
        public virtual DbSet<WF_CaseNotifications> WF_CaseNotifications { get; set; }
        public virtual DbSet<WF_CasePropertyValues> WF_CasePropertyValues { get; set; }
        public virtual DbSet<WF_CaseSteps> WF_CaseSteps { get; set; }
        public virtual DbSet<WF_CaseUserActions> WF_CaseUserActions { get; set; }
        public virtual DbSet<WF_CountryArchivePaths> WF_CountryArchivePaths { get; set; }
        public virtual DbSet<WF_FlowCases_Attachments> WF_FlowCases_Attachments { get; set; }
        public virtual DbSet<WF_FlowConditions> WF_FlowConditions { get; set; }
        public virtual DbSet<WF_FlowGroups> WF_FlowGroups { get; set; }
        public virtual DbSet<WF_FlowPropertys> WF_FlowPropertys { get; set; }
        public virtual DbSet<WF_Flows> WF_Flows { get; set; }
        public virtual DbSet<WF_FlowSteps> WF_FlowSteps { get; set; }
        public virtual DbSet<WF_FlowTypes> WF_FlowTypes { get; set; }
        public virtual DbSet<WF_LastStepNotifyUser> WF_LastStepNotifyUser { get; set; }
        public virtual DbSet<WF_NoApproverConditions> WF_NoApproverConditions { get; set; }
        public virtual DbSet<WF_Secretary> WF_Secretary { get; set; }
        public virtual DbSet<WF_StepConditions> WF_StepConditions { get; set; }
        public virtual DbSet<WF_StepGroupConditions> WF_StepGroupConditions { get; set; }
        public virtual DbSet<WF_StepGroups> WF_StepGroups { get; set; }
        public virtual DbSet<WF_StepNotificateUsers> WF_StepNotificateUsers { get; set; }
        public virtual DbSet<WF_TemplatePropCode> WF_TemplatePropCode { get; set; }
        public virtual DbSet<BLSShopView> BLSShopView { get; set; }
        public virtual DbSet<BLSSKUMaster> BLSSKUMaster { get; set; }
        public virtual DbSet<GlobalUserView> GlobalUserView { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<WF_FlowCases> WF_FlowCases { get; set; }
    }
}
